#+title: Infolettre Lab IA n°14
#+date: 2021-07-27
#+author: Etalab
#+layout: post
#+draft: false

L'infolettre du Lab IA est une lettre d'information mensuelle sur les actualités du Lab IA d'Etalab, *les échanges, expérimentations, rencontres et outils autour de l'usage des données et de l'IA pour améliorer l'action publique*. Elle s’adresse à la communauté du Lab IA : participants aux [[https://www.etalab.gouv.fr/intelligence-artificielle-decouvrez-les-15-nouveaux-projets-selectionnes][AMI IA 1 et 2]], data scientists de l'administration, chercheurs et agents publics intéressés par la science des données et l'IA.

Vous pouvez vous y inscrire depuis [[https://infolettres.etalab.gouv.fr/subscribe/lab-ia@mail.etalab.studio][ce lien]], [[https://etalab.github.io/infolettre-lab-ia/][lire les infolettres précédentes]] et proposer des contenus pour les prochaines éditions.

/Ci-dessous/ : 

- *Programme du prochain datadrink de la rentrée le 9 septembre*
- *A la rentrée, le Lab IA lancera un nouvel accompagnement IA*
- *Retour sur la journée de présentation des stagiaires Lab IA*
- *Revisionner le dernier datadrink*
 
 
/L'administration recrute !/

* Le Lab IA recrute son lead data scientist. Voir l'offre [[https://www.etalab.gouv.fr/le-lab-ia-recrute-sa-ou-son-lead-data-scientist][ici]]
* SignauxFaibles recrute. Voir l'offre [[https://beta.gouv.fr/recrutement/2021/07/01/un.e.data.scientist.signaux-faibles.html][ici]]
* Le datalab du ministère de l'Intérieur recrute 
    * une [[https://place-emploi-public.gouv.fr/offre-emploi/dnum-sdit-labd-75---data-engineer-hf-reference-MINT_BS075ACA-28510/][offre]] pour un data engineer 
    * une [[https://place-emploi-public.gouv.fr/offre-emploi/dnum-sdit-bld-75---data-scientist-hf-reference-MINT_BS075ACA-28512/][offre]] pour un data scientist 
    * une [[https://place-emploi-public.gouv.fr/offre-emploi/dnum-sdit-labd-architecte-75---devops-au-laboratoire-de-la-donnee-hf-reference-MINT_BS075ACA-28504/][offre]] pour un dev ops 
* Le SGDSN recrute (à confirmer, contact Paul-Antoine)
* Le ministère de la Défense recrute un expert de haut niveau. Voir l'offre [[https://place-ep-recrute.talent-soft.com/Pages/Offre/detailoffre.aspx?idOffre=658716&idOrigine=502&LCID=1036&offerReference=2021-658716][ici]].
* Stage en computer vision au ministère de l'Intérieur. Voir l'offre [[https://www.pass.fonction-publique.gouv.fr/offre/data-scientist-computer-vision][ici]].

/Une initiative de la mission Talents de la DINUM pour attirer les profils juniors /

L’opération #VisMonJob est lancée, elle vise à améliorer la notoriété des administrations en tant qu’employeur du numérique auprès des juniors. Des étudiants en M1/M2 se formant au numérique viendront passer une journée en immersion dans les services de l’Etat, à la rencontre de nos collaborateurs-ambassadeurs. Inscription [[https://sgmap.sphinxdeclic.com/surveyserver/s/MGTK-HQJWYFPJ/VisMonJob-ambassadeurs][ici]]. 


/Prochains événements/ : 
Le datadrink de la rentrée aura lieu le jeudi 9 septembre de 16h30 à 17h30. Inscriptions [[https://www.eventbrite.fr/e/billets-datadrink-du-lab-ia-etalab-163210068709][ici]]. 
Au programme: 
- Valentin Barrière (Commission Européenne) : prédire l’utilisation des terres agricoles à partir de données satellites (avec Food protection).
- Clément Biron, Elsa Trujillo, Martin Ratinaud (mission Beta.gouv et Ambassadeur du Numérique): évaluer et chiffrer les campagnes de manipulation de l’information sur Twitter (suivi de hashtags, visualisation des campagnes, détection de bots).
- Oana Balalau (INRIA): analyser l'impact de la propagande dans six grands forums politiques sur Reddit, qui ciblent un public diversifié aux États-Unis et au Royaume-Uni


** A la rentrée, le Lab IA lancera un nouvel accompagnement IA 

Le Lab IA lancera en septembre un appel à candidatures pour permettre aux admnistrations lauréates de bénéficier d'un accompagnement recherche en Intellifence Artificielle. Petit frère de l'AMI IA, l'accompagnement recherche s'inscrit dans la collaboration que la DINUM et l'Inria ont entamée en 2020. 

L'accompagnement recherche permettra aux datascientist de l'administration de bénéficier du soutien de chercheurs et d'ingénieurs de recherche de l'Inria pendant une durée de un an. Pour les datascientists de l'administration, cet accompagnement sera l'occasion de prendre du recul sur leurs défis et d'explorer de nouvelles approches à leurs problématiques, dont certaines peuvent se révéler trop complexes ou ambitieuses pour être traitées dans l'emploi du temps quotidien. Pour les chercheurs, cet accompagenement leur permettra de tester leurs méthodes sur de nouveaux jeux de données et de contribuer à des missions de service public. Nous pensons que ce format mènera à des collaborations fructueuses entre l'administration française et le centre de recherche prestigieux qu'est Inria. 

Pour participer, il vous faudra décrire votre problématique et son contexte, expliquer en quoi l'IA permet d'apporter une solution au problème et fournir un descriptif de vos données pour la première semaine du mois d'octobre. L'équipe du Lab IA sélectionnera ensuite les équipes Inria qui travailleront sur le projet pour commencer les projets au début de l'année 2022. Nous informererons des modalités de candidatures à la rentrée (les candidatures seront à déposer sur Démarches Simplifiées de début septembre à début octobre). 

** Retour sur la journée de présentation des stagiaires Lab IA

Le Lab IA, dont l'une des missions principales est d'accompagner les administrations dans la mise en place de solutions d'Intelligence Artificielle, reçoit des demandes d'aide de la part de datascientists de l'administration sur des sujets spécifiques. Nous avons plusieurs moyens d'appuyer les équipes data sciences de l'administration : clinique de l'IA, mise en relation avec d'autres équipes ayant rencontré des problématiques similaires, fléchage vers des dispositifs d'accompagnement, mise en place de stages ou de missions dédiées. 

En ce moment, trois stagiaires encadrés par Oana Balalau, chercheuse à l'Inria et membre du Lab IA,  travaillent sur des problématiques que des administrations ont remontées au LabIA. Vendredi 9 Juillet dernier, une première réunion de restitution s'est tenue afin de partager les avancements de ces stages. 

Abdenour Chaoui, qui travaille sur l'amélioration de la brique PIAF, nous a présenté les algorithmes de re-ranking de documents sur lesquels il planche depuis plusieures semaines. Ces algorithmes permettront à PIAF de retrouver plus efficacement les documents pertinents dans une base de connaissance pour répondre à la question d'un utilisateur. 

Thomas Meunier, qui travaille sur les algorithmes de Signaux Faibles, nous a présenté son investigation des différents algorithmes qui pourraient rendre le modèle de Signaux Faibles plus robuste à la crise sanitaire. Ces travaux permettront à terme de mieux cibler les entreprises en difficulté afin de déclencher des dispositifs d'aide avant que l'entreprise ne fasse faillite, et ainsi faciliter le travail des agents sur le terrain. 

Lors de la prochaine édition de cette réunion de restitution, Maya Touzari nous présentera son travail avec le BRGM avec qui elle met en place un agent conversationnel permettant de renseigner les utilisateurs sur l'état de l'eau dans leur région via la plateforme Hub'eau. 

** Revisionner le dernier datadrink 

Vous pouvez retrouver l'ensemble des liens de rediffision de nos datadrink en ligne sur la page [[https://www.etalab.gouv.fr/communaute][communauté du Lab IA]]. 

Vous pouvez (re)-visionner [[https://visio.incubateur.net/playback/presentation/2.0/playback.html?meetingId=227cbb7905fce775cffaaa01d64d65a8c89bff85-1625149326635][ici]] l'édition du 1er juillet 2021. Les supports de présentation sont à retrouver via les liens suivants : [[https://speakerdeck.com/etalabia/20210701-datadrink-lectaurep][Lectaurep]], [[https://speakerdeck.com/etalabia/20210701-datadrink-mte-ecolab][projet NLP de l'Ecolab]], 
[[https://speakerdeck.com/etalabia/20210701-datadrink-knoweledgebase-labia][la base de connaissance du Lab IA]].
