#+title: Infolettre Lab IA n°17
#+date: 2022-02-25
#+author: Etalab
#+layout: post
#+draft: false

L'infolettre du Lab IA est une lettre d'information mensuelle sur les actualités du Lab IA d'Etalab, *les échanges, expérimentations, rencontres et outils autour de l'usage des données et de l'IA pour améliorer l'action publique*. Elle s’adresse à la communauté du Lab IA : participants aux [[https://www.etalab.gouv.fr/intelligence-artificielle-decouvrez-les-15-nouveaux-projets-selectionnes][AMI IA 1 et 2]], data scientists de l'administration, chercheurs et agents publics intéressés par la science des données et l'IA.

Vous pouvez vous y inscrire depuis [[https://infolettres.etalab.gouv.fr/subscribe/lab-ia@mail.etalab.studio][ce lien]], [[https://etalab.github.io/infolettre-lab-ia/][lire les infolettres précédentes]] et proposer des contenus pour les prochaines éditions.



  
** Les événements 

Prochain datadrink du *17 mars*. 
Inscription [[https://www.eventbrite.fr/e/billets-datadrink-du-17-mars-2022-274210540107][ici]].
Au programme : 
- *Benjamin Barralon, Sarah Cocher et Beryl Koller du Laboratoire des données du Ministère de l’Intérieur* nous présenteron *Basegun*, une solution d’IA permettant d’identifier et classer instantanément une arme sur le terrain. 
- *Félicien Vallet (responsable AI à la CNIL) et Clément Hénin (docteur en XAI de l’Inria, actuellement rapporteur à la Cour des Comptes)*: Deux outils conçus par Clément pendant sa thèse ont été mis à disposition d’agents du service des contrôles de la CNIL dans le cadre d'une user study. Celle-ci a permis d’évaluer sur le terrain l’efficacité de ces méthodes d’*XAI (IA explicable)* et a présenté à la CNIL le potentiel de ces nouvelles méthodes qui pourront notamment être utiles pour les futurs audits algorithmiques prévus par le projet européen sur l’IA. Si vous souhaitez tester les outils, la plateforme d’expérimentation en ligne est accessible à l’adresse suivante : http://algaudit.inrialpes.fr/

** L'administration recrute

- L'agence nationale de la sécurité informatique recrute un ingénieur des données, plus d'informations [[https://talents.ssi.gouv.fr/offresdemploi/ingenieur-responsable-technique-de-la-conception-d-outils-d-analyse-en-investigation-numerique-f-h][ici]] 


** Ressources 

- Formation *scickit learn* de l'INRIA : Développé par l'équipe créatrice de scikit-learn, le cours "Machine learning in Python with scikit-learn" se présente sous la forme d’un Mooc (Massive Open Online Course) diffusé sur la plateforme FUN, en anglais, gratuit et accessible à toute personne ayant des compétences de base en programmation Python. 



** Intelligence artificielle : 5 lauréats de l’appel à manifestation d’intérêt “Accompagnement recherche” !

Après les deux premiers appels à manifestation d’intérêt pour expérimenter l’IA dans l’administration, le Lab IA a lancé, le 6 septembre 2021, un AMI « Accompagnement Recherche ». Cet AMI répond à trois finalités 
- Faire bénéficier les lauréats de l’expertise des partenariats privilégiés du Lab IA issus du monde de la recherche, notamment avec l’Inria qui travaille en étroite collaboration avec la DINUM depuis avril 2020 ;
- Lever les éventuels verrous technologiques rencontrées par les administrations lauréates dans l’implémentation d’une solution IA à leurs besoins existants ;
- Mettre la recherche en intelligence artificielle au service de la transformation publique.

** 5 lauréats de tous horizons sur des sujets variés :

Sur les huit candidatures exprimées, cinq ont été retenues pour bénéficier de l’accompagnement recherche du Lab IA.

*Commission nationale de l'informatique et des libertés : Aide à l’analyse sur la lecture des Analyses d’Impact relatives à la Protection des Données.*

Les traitements informatiques utilisant des données à caractère personnel se trouvent à la croisée de nombreux textes juridiques. Bien que le RGPD ait supprimé une grande partie des formalités déclaratives auprès de la CNIL, certaines obligations demeurent. Parmi ces obligations figurent l’encadrement juridique des transferts hors UE, qui peuvent être réalisés au moyen des Binding Corporate Rules (BCR) et les Analyse d’Impact relatives à la Protection des Données (AIPD). Ce sont des dossiers complexes, de plusieurs dizaines de pages, majoritairement en anglais, comportant obligatoirement les “binding corporate rules” et les documents supports permettant de justifier de la réalité des procédures mises en place par l’organisme. Elles nécessitent ainsi une instruction lourde tant pour la CNIL que pour les entreprises. L’objectif de ce projet est de faciliter l’instruction des dossiers reçus par la CNIL en permettant de repérer automatiquement, dans les documents soumis à l’approbation de la CNIL, les paragraphes d’intérêt pour les agents.

*Ministère de la transition écologique : Aide à l’analyse grâce à la recherche intelligente dans les dossiers de projets soumis à évaluation environnementale.* 

Les auditeurs des autorités environnementales régionales (MRAe) et nationale (Ae) instruisent chaque année de l’ordre de 1000 dossiers de projets soumis à évaluation environnementale (parcs éoliens, installations industrielles, aménagements urbains ...). Le dossier d'un projet est composé de nombreux documents pdf, dont notamment l’étude d’impact du projet, et comporte jusqu'à plusieurs milliers de pages. L'auditeur doit y identifier les aspects à améliorer pour éviter, réduire ou compenser les impacts environnementaux du projet. Les MRAe Ae sont tenues de rendre leur avis sur les dossiers qui leur sont soumis dans un délai contraint, qui n’est parfois pas respecté faute de ressources humaines. L'Ecolab du MTE porte le développement d'un outil pour aider les auditeurs de MRAe Ae à instruire efficacement les dossiers.


*Ministère de l’Intérieur : Cluster Vec.*

Chaque année, 20 000 000 clichés issus des radars sont envoyés à l’Agence Nationale du Traitement Automatisé des Infractions (ANTAI) et au Centre Automatisé de Contestation des Infractions Routières (CACIR) pour traitement. Parallèlement, près de 10 000 usagers reçoivent un avis de contravention alors qu’ils n’ont pas commis l’infraction routière correspondante. Dans de nombreux cas, c’est une usurpation de plaque qui est à l’origine de l’erreur. La contravention est alors envoyée au titulaire du certificat d’immatriculation renseigné dans le Système d’Immatriculation des Véhicules (SIV) et non à la personne ayant réellement commis l’infraction. Une technique existe pour repérer les plaques usurpées : comparer le numéro de la plaque au modèle du véhicule qui doit y être associé, également renseigné dans le SIV. Si les deux éléments ne correspondent pas, l’ANTAI peut effectuer un signalement et éviter de sanctionner un usager n’ayant commis aucune infraction. Grâce à l’algorithme IA flash cette détection est possible par l’identification automatique du modèle du véhicule sur le cliché de l’infraction. Cependant le réentrainement de ce modèle supervisé par l’ajout de nouvelles données annotées manuellement est couteux en temps. L’objectif du projet est d’explorer les nouvelles possibilités d’entrainement non supervisé en computer vision afin de faciliter la maintenance du modèle.

*Bureau de Recherches Géologiques et Minières : LoggingIA.*

Le BRGM est l’établissement public de référence pour le sous-sol. Au travers de la Banque du Sous-Sol (BSS), le BRGM collecte, héberge et diffuse les données géologiques et environnementales, qui constituent une matière première pour des applications au service des citoyens. Les données sont à ce jour non structurées donc peu valorisables. Seule la localisation des ouvrages y est présentée, quelques métadonnées sont incluses, et des documents scannés (en raster) y sont joints. Ces documents incluent des logs de forage, parfois des diagraphies, plus rarement des carottes scannées. Les informations de ces scans constituent un gisement de connaissance immense et non valorisé (pour la connaissance du public, des décideurs, des entreprises de génie civil). L’objectif du projet est de mettre à disposition l’information géologique. Cela passe par la dataïfication des ‘logs’ de forages (diagrammes de représentation verticale de séries stratigraphiques) et des diagraphies (mesure avec des ondes des roches traversées), et à terme la déduction par apprentissage des natures de roches traversées et la reconnaissance des profondeurs et des vocabulaires adossés aux registres.

*Secrétariat Général de le Défense et de la Sécurité Nationale : Solution de veille de sources d’actualité ouvertes pour améliorer l’alerte et la prise de décision.*

Le Secrétariat général de la défense et de la sécurité nationale compte parmi ses missions la veille des menaces et des risques qui pèsent sur la France. Il confie cette mission en particulier au Bureau de veille et d’alerte (BVA), au sein de la Direction de protection et de sécurité de l’Etat. Le BVA participe ainsi, et uniquement à partir de sources ouvertes d’Internet, à l’alerte et à la bonne information des décideurs gouvernement aux 24 heures sur 24. L’objectif est de développer un outil d’automatisation de la veille sur internet. Cet outil permettra : 1) un passage à l’échelle sur la quantité de flux traitée (quantité d’informations évaluée), qui aujourd’hui est bloqué par le nombre d’agents du bureau, et qui sera débloqué par l’outil, la capacité de stockage des données et la puissance de calcul ; 2) aux agents de consacrer plus de temps à des tâches à plus forte valeur ajoutée, en particulier d’accompagner la montée en puissance du BVA sur la synthèse et l’analyse.

*** Un accompagnement scientifique sur tous les domaines de l'IA

Les lauréats de l’accompagnement recherche bénéficient d’un accompagnement scientifique piloté par le Lab IA pour réaliser un prototype fonctionnel. Les aspects techniques seront confiés à des personnes rattachées à des équipes de recherche (ingénieurs de recherche, positions temporaires, post-doc, doctorants le cas échéant).

Les projets portent sur tous les domaines de l’IA (le traitement automatique du langage naturel, la vision par ordinateur, l’apprentissage automatique sur des données structurées) et concernent aussi bien le développement qu’un algorithme que l’amélioration de l’explicabilité ou la correction d’un biais algorithmique. Les lauréats sont accompagnés sur une durée d’un an.

A l’issue de l’accompagnement, le Lab IA et le lauréat auront un retour d’expérience suffisant pour être en mesure de décider si l’expérimentation est concluante ou non et le cas échéant de prendre une décision pour prolonger l’expérimentation, industrialiser le produit ou l’abandonner. 

*** Composition du jury

Le jury de sélection était composé des membres suivants : 
- Laure Lucchesi, Directrice de Etalab
- Bertrand Braunschweig, Ex-Directeur de la mission Inria de coordination du programme national de recherche en intelligence artificielle
- Ioana Manolescu, Directrice scientifique du Lab IA
- Paul-Antoine Chevalier, Responsable du Lab IA
- Oana Balalau, Chercheuse Inria
- Robin Reynaud, Chef de projet Lab IA

** A vos idées !
Le printemps n'est pas si loin, le bon moment pour l'InfoLettre du Lab IA de faire peau neuve !
Vous avez des envies de rubriques nouvelles, des attentes, des suggestions à nous faire part. N'hésitez à nous le faire savoir : lab-ia@data.gouv.fr


