#+title: Infolettre Lab IA n°16
#+date: 2021-11-5
#+author: Etalab
#+layout: post
#+draft: false

L'infolettre du Lab IA est une lettre d'information mensuelle sur les actualités du Lab IA d'Etalab, *les échanges, expérimentations, rencontres et outils autour de l'usage des données et de l'IA pour améliorer l'action publique*. Elle s’adresse à la communauté du Lab IA : participants aux [[https://www.etalab.gouv.fr/intelligence-artificielle-decouvrez-les-15-nouveaux-projets-selectionnes][AMI IA 1 et 2]], data scientists de l'administration, chercheurs et agents publics intéressés par la science des données et l'IA.

Vous pouvez vous y inscrire depuis [[https://infolettres.etalab.gouv.fr/subscribe/lab-ia@mail.etalab.studio][ce lien]], [[https://etalab.github.io/infolettre-lab-ia/][lire les infolettres précédentes]] et proposer des contenus pour les prochaines éditions.

/Ci-dessous/ : 

- *Programme du prochain datadrink de novembre en présentiel*
- *OpenLab Onyxia le 6 décembre au Lieu de la transformation publique*
- *Les candidatures au 3ème appel à projets "Utilisation de la donnée dans votre administration" de France Relance sont ouvertes*
- *Revisionner le dernier datadrink*
 

/Prochains événements/ 

- Appel à projets *"Utilisation de la donnée"* - Ateliers pour présenter votre projet à un membre de l'équipe le mercredi 10 novembre de 10h30 à 12h en ligne. Inscription [[https://www.eventbrite.fr/e/billets-ateliers-utilisation-de-la-donnee-dans-votre-administration-203953439227][ici]].
- *Datadrink en présentiel* le 19 novembre de 16h30 à 18h au Lieu de la transformation publique. Inscription [[https://www.eventbrite.fr/e/billets-datadrink-de-novembre-195897142627][ici]]. Pour ceux qui ne pourraient pas venir, une rediffusion webinaire est prévue. Inscrivez-vous pour recevoir le lien de rediffusion. 
    - *Lucas Verney (PEReN)* : conception d’un outil d’anonymisation (locale) des données d’utilisateurs de plateformes numériques afin de leur permettre de contribuer des informations sectorielles aux administrations.
    - *Alexis Eidelman (DARES)* et *Danielle Bourlange (INSEE)* : présentation des recommandations du rapport INSEE-DINUM sur la *valorisation des compétences data* dans l'administration. 
    
Le second sujet étant vaste, nous ne prévoyons que deux interventions pour cette session, afin de dédier plus temps à la deuxième intervention et aux échanges associés.  Les présentations seront suivies d'un moment convivial. 

- *OpenLab Onyxia* le 6 décembre 14h-17h au Lieu de la transformation publique avec l'INSEE. Plus de détails et inscriptions [[https://www.eventbrite.fr/e/billets-openlab-onyxia-n1-203811223857][ici]]. 


/L'administration recrute des data scientists !/ 
- Le Lab IA recrute son *lead data scientist* : voir l'offre [[https://www.etalab.gouv.fr/le-lab-ia-recrute-sa-ou-son-lead-data-scientist][ici]]. 
- Ingénieur d’études en production, traitement, analyse de données et enquêtes à l’observatoire à l'Université Paris-Saclay : voir l'offre [[https://www.emploipublic.fr/offre-emploi/offre-emploi-ingenieur-d-etudes-en-production-traitement-analyse-de-donnees-et-enquetes-a-l-observatoire-h-f-o-408373][ici]].

** OpenLab Onyxia le 6 décembre au Lieu de la transformation publique

Retrouvez [[https://www.eventbrite.fr/e/billets-openlab-onyxia-n1-203811223857][ici]] la page de l'événement pour vous inscire. 

[[https://onyxia.lab.sspcloud.fr/home][Onyxia]] est une *plateforme mutualisée de traitement de données*. Le datalab de l'INSEE propose aux statisticiens et aux data scientists de l’État un *catalogue de services* et un *environnement de travail simple, rapide et collaboratif*, permettant de lancer facilement ses outils et d’y connecter ses données et son code.

Au-delà des ressources techniques, le projet représente une opportunité pour les statisticiens publics de découvrir et d’adopter de *nouvelles méthodes de travail*. Il est aussi utilisé à des fins de *formations et d’auto-formations*.

Ce premier OpenLab, organisé conjointement par l'INSEE et le Lab IA d'Etalab, a pour objectif de rassembler une communauté d'utilisateurs potentiels, d'obtenir des retours utilisateurs et de mieux connaitre vos besoins et cas d'usage afin d'orienter les futurs développements.

Au programme :

- Présentation de l'outil Onyxia
- Ateliers
- Échanges et restitution

Vous êtes chercheur, agent public, étudiant, citoyen, spécialiste de l'IA ou non ? Venez participer au projet !


** Les candidatures au 3ème appel à projets "Utilisation de la donnée dans votre administration" de France Relance sont ouvertes 

Un troisième (et dernier) appel à projets du volet *"Utilisation de la donnée dans votre administration" (ITN5)* de France est relance est ouvert aux candidatures jusqu'au 19 novembre. Cet appel à projets est destiné aux directions d'administration ou aux opérateur en charge d'une politique publique souhaitant développer le recours à la donnée dans la décision et la performance publique. Cet appel à projets permet de cofinancer à hauteur de 75% les *projets de plus de 300 000 euros* en coût total. Un guichet ouvert en continu jusqu'à fin 2022 permet de cofinancer les projets de moins de 300 000 euros.  


Nous vous proposons de présenter votre projet et d'obtenir des retours d'un membre de l'équipe Plan de Relance le *mercredi 10 novembre de 10h30 à 12h*. Vous pouvez vous inscrire [[https://www.eventbrite.fr/e/billets-ateliers-utilisation-de-la-donnee-dans-votre-administration-203953439227][ici]].
L'événement se tiendra en ligne (les détails de connexion vous serons communiqués par mail le jour de l'événement, à l'adresse e-mail indiquée lors de l'inscription).  Afin que nous puissions organiser au mieux ces ateliers, pouvez-vous nous indiquer par mail à plan-de-relance@data.gouv.fr d'ici le 9 novembre à 15h si vous souhaitez présenter un projet lors de cet atelier. Le cas échéant, merci de nous indiquer le nom de votre administration et une brève description du projet. 

Ce dispositif vous est ouvert afin d'améliorer grâce à la donnée l'efficacité de l'action publique, développer une culture de la donnée, ou encore accroître la qualité des données mises à disposition du public ou d'autres administrations.
Plus d'informations sur [[https://france-relance.transformation.gouv.fr/96c0-developper-lutilisation-de-la-donnee-dans-vot][la page dédiée]] du site France Relance.
Vous pouvez contacter l'équipe en charge du volet «Utilisation de la donnée dans votre administration» du Plan de Relance numérique via plan-de-relance@data.gouv.fr. 

** Rediffusion du dernier datadrink

Vous pouvez revoir le datadrink du 9 septembre 
[[https://bbb-dinum-scalelite.visio.education.fr/playback/presentation/2.3/3f0ef841bc93cc5b892daa1197e861d0ef76569a-1634825927607][ici]]. 

- *Nicolas Stefanovitch* et *Guillaume Jacquet* (Commission Européenne):  Le Text Mining comme support pour l'analyse de consultations publiques. Retrouvez la présentation [[https://speakerdeck.com/etalabia/20211021-datadrink-textmining-ce][ici]].
- *Philippe Besse* (Professeur émérite à l'INSA Toulouse): Quelles implications la future réglementation de l'IA au niveau européen (telle que présentée notamment dans l'Artificial Intelligent Act) aura-t-elle sur le travail du data scientist  ? Retrouvez la présentation [[https://speakerdeck.com/etalabia/20211021-datadrink-besse-risquesia][ici]].


